import database
from datetime import date

cas_candidates = [
    {
        "id": "azcarrate-cassc-president",
        "name": "Azcarrate",
        "position": "President",
        "tagline": "Empowering student voices through academic rigor and global leadership.",
        "credentials": "ACADEMIC EXCELLENCE\n● University Scholar, University of the East\n● Tulong Dunong Program - UNIFAST Scholar\n● Graduated in Top 10% of Class, Senior High School\n● Consistent With High Honors, Senior High School (Grades 11-12)\n● Science, Technology, and Engineering (STE) Student, Junior High School\n● With High Honors and Conduct Awardee, Junior High School\n● Best in Science, Best in Communication Arts, and Best in Araling Panlipunan\n● 1st Place Pagsulat ng Sanaysay, 2nd Place Science Writer, and 3rd Place Editorial/Feature Writer\nEXTRA CURRICULARS\n● Secretary, UE-Caloocan Psychological Society\n● President, LISTO Club (Grade 12)\n● Vice President, LISTO Club (Grade 11)\n● Science, Technology, Engineering, and Mathematics Class Vice President\n● Classroom Auditor (Grade 12)\n● 3rd Runner Up, Stand Up and Deliver (Local Level)\n● Division Level Oratorical Speaker, 2023 Talents Fest\n● Graphic Designing and Social Media Manager Intern, NINE Company\n● High Distinction Certificate: Rhetoric: The Art of Persuasive Writing and Public Speaking, Harvard University\n● High Distinction Certificate: The Einstein Revolution, Harvard University\n● High Distinction Certificate: Building Personal Resilience: Managing Anxiety and Mental Health, Harvard University\n● High Distinction Certificate: Cell Biology: Mitochondria, Harvard University\n● High Distinction Certificate: Exercising Leadership: Foundational Principles, Harvard University\n● High Distinction Certificate: Introduction to Biology - The Secret of Life, Massachusetts Institute of Technology (MIT)\n● High Distinction Certificate: Connected Leadership, Yale University\n● High Distinction Certificate: Attaining Higher Education, Columbia University\n● High Distinction Certificate: The Psychology of Emotions, University of Cambridge\n● High Distinction Certificate: Introduction to Cognitive Psychology and Neuropsychology, University of Cambridge",
        "bio": "Empowering student voices through academic rigor and global leadership.",
        "council": "CASSC",
        "created_at": str(date.today()),
    },
    {
        "id": "corod-cassc-vp",
        "name": "Corod",
        "position": "Vice President",
        "tagline": "Cultivating a community of excellence through mental wellness and proactive leadership.",
        "credentials": "ACADEMIC EXCELLENCE\n● Student Academic Awards Recognition (2024-2025)\n● Overall With Honors, Senior High School (Grades 11-12)\n● With Honors, Junior High School (Grade 10)\nEXTRA CURRICULARS\n● Incumbent Auditor, CASSC (2025-2026)\n● Main Project Head, CASabay, CASkwela: Welcoming Week Event\n● Main Project Head, CASama: Mental Wellness Pop-up Event Series\n● Committee Member, CSC Treasury (2025-2026)\n● Committee Member, UECPS (2025-2026)\n● 1st Year Representative, UECPS (2024-2025)\n● Committee Member, CASSC Treasury (2024-2025)\n● Head Usher, 3rd Pinning Ceremony: Celebration of Honoring Milestones\n● Host, Alay ni Luwalhati sa mga Exceptional Children: Outreach Program (2026)\n● Research Presenter, 5th Punlasik Research Conference\n● Secretary, SHS Political Science Club\n● Grade 11 Class President\n● Participant, Leadership Camp 2024: Igniting the Flame of Integrity in Leadership",
        "bio": "Cultivating a community of excellence through mental wellness and proactive leadership.",
        "council": "CASSC",
        "created_at": str(date.today()),
    },
    {
        "id": "palomaria-cassc-secretary",
        "name": "Palomaria",
        "position": "Secretary",
        "tagline": "Bridging gaps in hospitality and tourism through research and service.",
        "credentials": "ACADEMIC EXCELLENCE\n● Graduated With Honors (Grade 12), Senior High School\nEXTRA CURRICULARS\n● Committee Member, ACTIONS under External Affairs (2026)\n● Logistics and Management Volunteer, Student Council (2024)\n● Research Presenter, 2nd Philippine International Tourism and Hospitality Research Conference (PITH-ReCon) at UST (2024)\n● Research Presenter, FEU Kain-Con (2024)\n● Research Participant, 5th Punlasik Research Conference (2024)\n● Seminar Host, Reshaping Career Goals in The Post-Pandemic Era (2024)",
        "bio": "Bridging gaps in hospitality and tourism through research and service.",
        "council": "CASSC",
        "created_at": str(date.today()),
    },
    {
        "id": "bangay-cassc-treasurer",
        "name": "Bangay",
        "position": "Treasurer",
        "tagline": "Dedicated to the spirit of fidelity and athletic excellence in student service.",
        "credentials": "ACADEMIC EXCELLENCE\n● Consistent With Honors (Grades 10, 11, and 12)\nEXTRA CURRICULARS\n● Incumbent 2nd Year Representative, CASSC\n● Secretary, UECCS (2024-2025)\n● Recipient, Fidelity Award (2023-2024)\n● Athlete of the Year (2023-2024)",
        "bio": "Dedicated to the spirit of fidelity and athletic excellence in student service.",
        "council": "CASSC",
        "created_at": str(date.today()),
    },
    {
        "id": "alvarado-cassc-auditor",
        "name": "Alvarado",
        "position": "Auditor",
        "tagline": "Championing student engagement through technical innovation and athletic drive.",
        "credentials": "ACADEMIC EXCELLENCE\n● Graduated With High Honors (Grade 12), Senior High School\n● Consistent Honor Student (Grades 10 and 11)\n● Conduct Awardee (Grade 10)\nEXTRA CURRICULARS\n● Volunteer, Alay ni Luwalhati sa mga Exceptional Children: Outreach Program (2026)\n● Technical Committee, CASiyahan Sa Silangan 2025: Pista ng Pagkakaisa\n● Committee Member, CAS Auditor Committee (2025-2026)\n● Documentary Committee, 3rd Pinning Ceremony: The Pursuit of Excellence in Psychology\n● Valorant Champion, Sinong Mas Angat Sinong Mas Sikat: Psychology E-Sports Edition (2024)\n● 2nd Place, Tagisan ng LaCAS Volleyball (2024)\n● Silver Medalist, Malprisaa NCR Division Meet Volleyball (2017)\n● Musical Theatre Champion, English Month Talkfest (2019)\n● Choral Reading Champion, English Month Talkfest (2018)\n● Epikong Dula Champion, Ibong Adarna (2018)\n● Grade 8 Class Vice President\n● Participant, Leadership Camp 2024: Igniting the Flame of Integrity in Leadership",
        "bio": "Championing student engagement through technical innovation and athletic drive.",
        "council": "CASSC",
        "created_at": str(date.today()),
    },
    {
        "id": "venales-cassc-pro",
        "name": "Veñales",
        "position": "PRO",
        "tagline": "Leading with integrity, empathy, and a passion for mental health awareness.",
        "credentials": "ACADEMIC EXCELLENCE\n● Consistent With High Honors (2022-2024)\n● Rank 3 Overall, Grade 11 HUMSS (2022-2023)\n● Overall Best in Research, Systems Plus Computer College (2023-2024)\n● Best in Research Project (HUMSS)\n● Consistent Subject Excellence Awardee: Earth and Life Science, Physical Science, Entrepreneurship, Social Sciences, Reading and Writing, English for Academic Purposes, 21st Century Literature, and Empowerment Technology\n● Perfect Attendance Awardee (2023-2024)\n● With Honors (Grade 10), Junior High School (2021-2022)\nEXTRA CURRICULARS\n● Presidential Committee, CAS (2024-2025)\n● Class Vice President (2023-2024)\n● Class Secretary (2022-2023)\n● Ms. HUMSS Ambassadress, Systems Plus Computer College (2023)\n● 1st Place, UE SWF Dance Competition\n● Student-Teacher Volunteer, Tara, ARAL! Tutorial Program (Brgy 70)\n● Host, Mental Health Seminar: Safeguarding the Mind in Times of Challenges\n● Host, Alay ni Luwalhati sa mga Exceptional Children: Outreach Program (2026)\n● Host, Psychkamustahan Event Program (UECPS)\n● Recipient, Trustworthy Award (Special Award for Integrity)",
        "bio": "Leading with integrity, empathy, and a passion for mental health awareness.",
        "council": "CASSC",
        "created_at": str(date.today()),
    },
    {
        "id": "rarugal-cassc-multimedia",
        "name": "Rarugal",
        "position": "Vice President for Multimedia",
        "tagline": "Strategic communication and multimedia leadership for the modern student body.",
        "credentials": "ACADEMIC EXCELLENCE\n● Valedictorian With Honors (Grade 12), Senior High School\n● Ranked 4th among all strands, Senior High School (2022-2023)\n● Consistent With Honors (Grades 10 and 11)\n● Best in Research Project and Diwa Awardee\n● Loyalty Awardee\nEXTRA CURRICULARS\n● Vice President for Multimedia, Association of Communication Students (2025-2026)\n● Chief Multimedia Officer, Silangan Film Circle (2025-2026)\n● Committee Member, PRO Committee - Central Student Council (2025-2026)\n● Event/Project Head, COMMTalks: Through the Lens Seminar/Workshop\n● Event/Project Head, Chika Comm Podcast: The Third Chapter\n● Vice Presidential Committee, CASSC (2024-2025)\n● Committee for Multimedia, Association of Communication Students (2024-2025)\n● Member, Lualhati League of Scholars, Red Cross Youth Council, and Youth for Animals\n● Media Team, CASiyahan sa Silangan and TRUE ICON (2024-2025)\n● Semi-Finalist, Diwa’s Kiwi Challenge Business Plan (2022-2023)\n● Class Business Manager (Grade 11)",
        "bio": "Strategic communication and multimedia leadership for the modern student body.",
        "council": "CASSC",
        "created_at": str(date.today()),
    },
    {
        "id": "dizon-cassc-secretary",
        "name": "Dizon",
        "position": "Secretary",
        "tagline": "A legacy of service, storytelling, and dedicated youth mentorship.",
        "credentials": "ACADEMIC EXCELLENCE\n● Student Academic Awards Recognition (2024-2025)\n● Quezon City Youth Scholar (2024-Present)\n● Consistent Honor Awardee and Top 4 of Graduating Class, Senior High School\n● With High Honors, Junior High School (Class of 2023)\n● English Speaker of the Year and Deportment Awardee\n● Champion, Filipino Declamation Competition (2022)\n● Champion, English Declamation Competition (2018)\nEXTRA CURRICULARS\n● Council Secretary, CASSC (2024-2025)\n● Presidential Committee Member, CSC (2025-2026)\n● Vice Presidential Committee Member, CASSC (2025-2026)\n● Project Head: CAS Alert Desk, Relief Drives, CASportsfest, and CASangga Lockers\n● Incoming Assistant Secretary, Church Council (2026-2027)\n● Affairs Head, Ecumenical Church Society (2025-2026)\n● President, Tambourine Ministry (2025-2026)\n● Sunday School and Vacation Church School Teacher (2018-Present)\n● Red Cross Volunteer (2023-2026)\n● UMYF Program Committee Member (2023-2025)\n● Member, Silangan Film Circle and Youth for Animals\n● Event Host, Summer Camps: Kaagapay (2024) and Intertwine (2025)\n● Classroom Secretary (2017-2020)\n● Technical Committee Staff, Christmas Institute (2025)\n● 3rd Place, Chess Competition (2020)",
        "bio": "A legacy of service, storytelling, and dedicated youth mentorship.",
        "council": "CASSC",
        "created_at": str(date.today()),
    },
    {
        "id": "delos-santos-cassc-pro",
        "name": "Delos Santos",
        "position": "PRO",
        "tagline": "Fostering growth through social development and active community engagement.",
        "credentials": "ACADEMIC EXCELLENCE\n● Consistent With Honors (Grades 10, 11, and 12)\n● Service Awardee, Pandayan Filipino Club (2022-2024)\nEXTRA CURRICULARS\n● President, Social Development and Services Committee, Church of Christ (2023-2024)\n● Local Secretary, Church of Christ (2022-Present)\n● President, Dako ng Herrera, Children Worship Services (2026-Present)\n● Key Officer Treasurer, Pandayan Filipino Club, New Era University (2023-2024)\n● HUMSS Coordinator, Pandayan Filipino Club (2022-2023)\n● Outreach Chairperson, City of Malabon University Chapter, CBI (2020-2022)\n● Member, UE-Caloocan Psychological Society (2024-2026)\n● Documentation Committee, Alay ni Luwalhati Outreach Program (2026)\n● Facilitator, NEU Year End Socializing (2022)\n● MVP and Mythical 3, Basketball Girls Intramurals (2020)\n● Participant, Safeguarding the Mind in Times of Challenges Seminar (2026)",
        "bio": "Fostering growth through social development and active community engagement.",
        "council": "CASSC",
        "created_at": str(date.today()),
    },
    {
        "id": "sison-cassc-rep",
        "name": "Sison",
        "position": "1st Year Representative",
        "tagline": "Consistent performance and dependable representation for the student body.",
        "credentials": "ACADEMIC EXCELLENCE\n● With Honors (Grade 12), Senior High School\n● Conduct Awardee (Grade 10)\nEXTRA CURRICULARS\n● Incumbent 1st Year Representative, CASSC (2nd Semester)\n● Secretarial Committee, CASSC (1st Semester)\n● Class Representative (2024-2025)\n● Member, UE-Caloocan Psychological Society (2024-2025)",
        "bio": "Consistent performance and dependable representation for the student body.",
        "council": "CASSC",
        "created_at": str(date.today()),
    },
]

for candidate in cas_candidates:
    database.save_candidate(candidate)
print("CAS candidates added.")
